name: flutter_mapkit_js
description: "A Flutter package that provides integration with MapKit JS, allowing you to embed interactive maps in your Flutter web applications."
version: 0.2.0
homepage: https://github.com/zuvola/flutter_mapkit_js

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mapkit_js: ^0.3.0

  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
